### ISSUE TITLE
Need to add Gaussian adapter.

### ISSUE THREAD

**Issue by PaulWAyers** [theochem/denspart#7]

**Comment by tovrstra** [comment]
There is an example showing how to interface to Gaussian, see https://github.com/theochem/denspart/tree/master/examples/horton3. Any wavefunction that can be read with IOData can be used as input. Is this what you meant?

**Comment by PaulWAyers** [comment]
Yep, this is what I meant. Sorry, I missed it...even though it was documented in the readme.

**Comment by tovrstra** [comment]
No problem. The README is rather extended because I did not feel like writing proper documentation yet. I've added working hyperlinks to the examples, which should make it a little easier.
